### ISSUE TITLE
Licensing for OSCDIMG

### ISSUE THREAD

**Issue by jssuttles** [Studisys/Bootable-Windows-ISO-Creator#1]
Hey, 
How do you deal with Windows licensing as shown on the oscdimg tool?

> OSCDIMG 2.54 CD-ROM and DVD-ROM Premastering Utility
> Copyright (C) Microsoft, 1993-2007. All rights reserved.
> Licensed only for producing Microsoft authorized content.

Thanks!

**Comment by Studisys** [comment]
Hello, sorry for late reply.

AFAIK I developed this script without intending to publish it on GitHub first and as you mention it, I forgot to remove it as per the licensing.

I removed it with the most recent commit and will (one day, if I get the time and head for this) redirect users to download the Windows AIK from Microsoft which contains oscdimg.

Thanks for your report ! (and sorry for my late response). 😁👍
